cohort_schedules/C02_classroom.md, cohort_schedules/C03_classroom.md
Oops. I was trying to complete my understanding of this pull request/merge cycle and accidentally recreated a branch I previously merged. I'm going to merge this one in and then work off master. If I'm doing this wrong, help me! Bookis, I'll talk to you about it next week. Sorry if anyone else is getting these notifications too.
=> ../topic_resource links

cohort_schedules/C02_internship.md
@sudocrystal @jnf @kariabancroft Do we have a PR process for changes to curriculum? Should we? Anyway, here's a small PR. :)
=> Adds Crystal's video link.

rubrics/week_1_calculator.md
Not sure if this is better; what do yinz think?
=> Tweak the layout of the rubric to make the examples easier to read.

rubrics/week_1_calculator.md
This isn’t complete yet, but so you can see what I’m doing…
=> Fleshing out Code Quality

rubrics/week_2_hangman.md
Trying to match https://github.com/Ada-Developers-Academy/daily-curriculum/commit/88a9fe9c24be5006925887e09c351eef06a338fa
=> Reformat hangman rubric to match others

topic_resources/scrabble.md
=> Update Scrabble requirements to match new patterns

rubrics/personal_website.md, topic_resources/bank_accounts.md, topic_resources/complexity.md, topic_resources/personal-website-overview.md, topic_resources/sinatra-blog.md
Update some Big O Stuff
Add inheritance project
Update rubric for personal website
=> Week 4 & 5

topic_resources/nix.md
A few additional details and some tips for the all important `cd` command.
=> More nix help

cohort_schedules/C03_classroom.md, topic_resources/intermediate-css.md
CSS Intermediate is in progress - just wanted to put in the list of intermediate topics
Also needed to update the C3 classroom schedule
=> Updates - CSS In progress

topic_resources/http-verbs.md, topic_resources/submitting-forms.md
Adds notes for discussions on HTTP Verbs, CRUD, and an intro to HTML forms.
=> Adding notes for discussions on HTTP Verbs, CRUD and HTML Forms.

topic_resources/ada_cooks.md
New topics to cover in lecture:
- File uploads (probably a live code with CarrierWave)
- `has_and_belongs_to_many` (most groups are using this in Betsy, I believe)
- View helpers and/or Decorator pattern (maybe?).
- factory_girl set up and testing example
=> Update the project requirements for Ada cooks.

cohort_schedules/C03_classroom.md, topic_resources/see-more.md, topic_resources/web-api-101.md
*Questions for Seemore*: 
1. Should we include RuboCop, Flog and Brakeman?
2. Should we use Waves (knowing that all/most groups probably won't get all of these things done) or should we go back to Break/Lunch/Din?
=> C3 Schedule + SeeMore Reqs

topic_resources/calculator.md, topic_resources/css-d&c.md, topic_resources/html-d&c.md, topic_resources/orange_tree.md, topic_resources/random_menu.md, topic_resources/solar-system.md, topic_resources/word-guess.md
This PR contains restructured assignments using the baseline paradigm that we discovered later in C3. If these are good we will create repos for them in the "Gold" org to create the C4 forks from.
=> C4 Assignment Prep

topic_resources/rails/views-101.md
Remove sections on defining your own helpers and using partials.
=> Update Rails Views topic resource

topic_resources/javascript/javascript-103.md, topic_resources/javascript/javascript-104.md
- update prototypes discussion
- switch 103 and 104
=> tweak js stuffs

README.md, cohort_schedules/C04_internship.md
First pass at this schedule @alexandraho
=> C4 schedule for internship times

topic_resources/consuming-an-api.md
openweather no requires an api key.
=> update required api key directions

topic_resources/code_reviewing.md
This is a small topic resource for my lecture to C4 about how to do code reviewing for C5's projects.
=> Topic Resource: Code Reviewing

cohort_schedules/C06_classroom.md
Remove Node Express
Add Backbone
Remove details on first two weeks
=> Update the classroom calendar

cohort_schedules/C07_classroom.md
Things I've changed:
- Updated the calendar to match C7
- Expanded the descriptions of some weeks
- Organize the calendar by unit
Things I've added:
- Overview of the course
- Short description and expected outcomes for each unit
=> Update and expand the syllabus for C7
